name: Dump Architectures
on:
  - push
jobs:
  aarch64_job:
    runs-on: ubuntu-18.04
    name: Dump on ${{ matrix.distro }} ${{ matrix.arch }}

    # Run steps on a matrix of 3 arch/distro combinations
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: fedora_latest
          - arch: ppc64le
            distro: fedora_latest
          - arch: s390x
            distro: fedora_latest
    steps:
      - uses: uraimo/run-on-arch-action@v2.1.1
        name: Dump it
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          shell: /bin/sh
          run: |
            cat /proc/cpuinfo

